### ISSUE TITLE
[Bug]: AttributeError: object has no attribute 'get'

### ISSUE THREAD

**Issue by astapchik** [Puyodead1/udemy-downloader#175] opened 2023-08-07 18:50 UTC
### What happened?

the course has such a structure, as soon as it reaches test1, an error appears and further parsing and downloading does not go on, what needs to be corrected to skip these tests

![2023-08-07_213952](https://github.com/Puyodead1/udemy-downloader/assets/17789165/6e7017e7-089c-4dfe-9071-439c44a5f361)

![2023-08-07_213503](https://github.com/Puyodead1/udemy-downloader/assets/17789165/a21161fb-b671-45e6-8e20-0b8d2ab6fa0f)

### Expected Result

There will be no errors in the picture

### Branch

master/main

### What operating systems are you seeing the problem on?

Windows

### Relevant log output

```shell
No response
```

### Other information

No response

**Comment by Puyodead1** [comment] 2023-08-07 21:10
I'll have to look into this, in the meantime, you can either edit _udemy.json and remove that particular assets data, or turn off downloading assets entirely.

**Comment by tuha1994** [comment] 2023-08-11 04:50
![image](https://github.com/Puyodead1/udemy-downloader/assets/127083599/8ad59590-8deb-4327-88dc-63ba5210e080)
help me fix it .thanks you

**Comment by Puyodead1** [comment] 2023-08-11 21:59
> ![image](https://github.com/Puyodead1/udemy-downloader/assets/127083599/8ad59590-8deb-4327-88dc-63ba5210e080)
> 
> help me fix it .thanks you

Read what it says... it's pretty obvious what is missing. It needs to be named shaka-packager.exe

**Comment by Fovty** [comment] 2023-08-20 16:25
The problem is still present in 1.2.11. Occurred while trying to download a quiz

**Comment by astapchik** [comment] 2023-08-20 16:41
> The problem is still present in 1.2.11. Occurred while trying to download a quiz

i just edited _udemy.json and threw quiz out of it

**Comment by Puyodead1** [comment] 2023-08-20 18:11
This should be fixed in the latest commit, let me know if this works or not

**Closed** 2023-08-20 18:10 UTC
Labels: bug

**Comment by Fovty** [comment] 2023-08-20 19:19
Yes, can confirm the latest commit fixed it. It's now working perfectly fine, thanks.

**Comment by Puyodead1** [comment] 2023-08-20 19:26
> Yes, can confirm the latest commit fixed it. It's now working perfectly fine, thanks.

great!
