### ISSUE TITLE
[Bug]: feat/refactor branch fails to download html 

### ISSUE THREAD

**Issue by auoie** [Puyodead1/udemy-downloader#218] opened 2024-04-25 18:07 UTC
### What happened?

Video lessons were downloaded successfully. HTML lessons were not downloaded.

### Expected Result

Seems like an issue in commit `1b1b5d81bd8147e693d147402d2aecd04c85b191`.

### Branch

master/main

### What operating systems are you seeing the problem on?

Linux/Unix

**Comment by lol-oil-11** [comment] 2024-06-27 10:33
hey, 
i am not able to download some things i am getting an error
![BUG](https://github.com/Puyodead1/udemy-downloader/assets/174010181/8c7820f0-8c91-4d47-afb3-33e15e316a1a)

anyone can help me out?

**Comment by Puyodead1** [comment] 2024-06-27 15:04
`Key not found` its pretty clear what the issue is... you do not have a decryption key specified for the course.

**Comment by Puyodead1** [comment] 2024-08-29 04:40
this should be resolved in 2d6a3020aab0612630fd650587c05b5d89b0892c

**Closed by Puyodead1** 2024-08-29 04:40 UTC
Labels: bug
