### ISSUE TITLE
[Bug]: Udemy Says: 'NoneType' object has no attribute 'json'

### ISSUE THREAD

**Issue by MJ-DEV91** [Puyodead1/udemy-downloader#82] opened 2021-12-16 15:53 UTC
### What happened?

I tried to download a course with the below command:
python main.py -c https://www.udemy.com/course/docker-hands-on/learn/ --download-assets --download-captions -b ******************************************************* 
but I faced this error:
```
Login Success
> Fetching course information, this may take a minute...
Failed request https://www.udemy.com/api-2.0/users/me/subscribed-courses?fields[course]=id,url,title,published_title&page=1&page_size=500&search=docker-hands-on
403 Forbidden, retrying (attempt 0 )...
Failed request https://www.udemy.com/api-2.0/users/me/subscribed-courses?fields[course]=id,url,title,published_title&page=1&page_size=500&search=docker-hands-on
403 Forbidden, retrying (attempt 1 )...
Failed request https://www.udemy.com/api-2.0/users/me/subscribed-courses?fields[course]=id,url,title,published_title&page=1&page_size=500&search=docker-hands-on
403 Forbidden, retrying (attempt 2 )...
Failed request https://www.udemy.com/api-2.0/users/me/subscribed-courses?fields[course]=id,url,title,published_title&page=1&page_size=500&search=docker-hands-on
403 Forbidden, retrying (attempt 3 )...
Failed request https://www.udemy.com/api-2.0/users/me/subscribed-courses?fields[course]=id,url,title,published_title&page=1&page_size=500&search=docker-hands-on
403 Forbidden, retrying (attempt 4 )...
Failed request https://www.udemy.com/api-2.0/users/me/subscribed-courses?fields[course]=id,url,title,published_title&page=1&page_size=500&search=docker-hands-on
403 Forbidden, retrying (attempt 5 )...
Failed request https://www.udemy.com/api-2.0/users/me/subscribed-courses?fields[course]=id,url,title,published_title&page=1&page_size=500&search=docker-hands-on
403 Forbidden, retrying (attempt 6 )...
Failed request https://www.udemy.com/api-2.0/users/me/subscribed-courses?fields[course]=id,url,title,published_title&page=1&page_size=500&search=docker-hands-on
403 Forbidden, retrying (attempt 7 )...
Failed request https://www.udemy.com/api-2.0/users/me/subscribed-courses?fields[course]=id,url,title,published_title&page=1&page_size=500&search=docker-hands-on
403 Forbidden, retrying (attempt 8 )...
Failed request https://www.udemy.com/api-2.0/users/me/subscribed-courses?fields[course]=id,url,title,published_title&page=1&page_size=500&search=docker-hands-on
403 Forbidden, retrying (attempt 9 )...
Udemy Says: 'NoneType' object has no attribute 'json' on https://www.udemy.com/api-2.0/users/me/subscribed-courses?fields[course]=id,url,title,published_title&page=1&page_size=500&search=docker-hands-on
```

### Expected Result

somehow this problem has a connection with IP address, if I use a VPN, then it works fine and starts downloading (everything is the same, except the IP!)

### Branch

master/main

### What operating systems are you seeing the problem on?

Windows

**Comment by Puyodead1** [comment] 2021-12-18 14:54
Are you able to use the udemy website without a vpn?

**Comment by MJ-DEV91** [comment] 2021-12-18 15:14
Yeah, absolutely

**Comment by Puyodead1** [comment] 2021-12-20 19:56
> Yeah, absolutely

still having this problem? I'm not sure what would be causing this issue. Please check that you are using the latest version of the master branch. I would also suggest turning off your VPN, logging out of the Udemy website, logging back in and getting a new bearer token (just in case the other token is tied to your VPN)

**Comment by MJ-DEV91** [comment] 2021-12-25 18:31
I just checked the master branch once again and I got a new token with VPN off, it's still the same.

**Comment by Puyodead1** [comment] 2021-12-26 00:04
> I just checked the master branch once again and I got a new token with VPN off, it's still the same.

Are you signed into the right account when you obtain the bearer token?

**Comment by MJ-DEV91** [comment] 2021-12-26 04:59
> > I just checked the master branch once again and I got a new token with VPN off, it's still the same.
> 
> Are you signed into the right account when you obtain the bearer token?

yeah, believe me, the only difference is using the VPN.

**Comment by Puyodead1** [comment] 2021-12-26 23:07
> > > I just checked the master branch once again and I got a new token with VPN off, it's still the same.
> > 
> > 
> > Are you signed into the right account when you obtain the bearer token?
> 
> yeah, believe me, the only difference is using the VPN.

In that case, I have no idea what the issue could be. the only thing i can think of would be something related to geo-location.

**Comment by mahdisky** [comment] 2021-12-27 17:59
i have this problem,
i used the vpn and the no vpn

**Comment by Puyodead1** [comment] 2021-12-27 18:03
> i have this problem, i used the vpn and the no vpn

what version of the tool are you using? `python main.py -v`

**Comment by mahdisky** [comment] 2021-12-27 19:15
version 1.1.4

**Comment by MJ-DEV91** [comment] 2021-12-28 17:14
> In that case, I have no idea what the issue could be. the only thing i can think of would be something related to geo-location.
I'm not sure if it has something to do with that,
this is the error that I'm getting:
```
[08:38:14] [udemy-downloader] [_get:856] ERROR: 403 Forbidden, retrying (attempt 8 )...
[08:38:14] [udemy-downloader] [_get:855] ERROR: Failed request https://www.udemy.com/api-2.0/users/me/subscribed-courses?fields[course]=id,url,title,published_title&page=1&page_size=500&search=kubernetes-microservices
[08:38:14] [udemy-downloader] [_get:856] ERROR: 403 Forbidden, retrying (attempt 9 )...
[08:38:15] [udemy-downloader] [_subscribed_courses:591] CRITICAL: Udemy Says: 'NoneType' object has no attribute 'json' on https://www.udemy.com/api-2.0/users/me/subscribed-courses?fields[course]=id,url,title,published_title&page=1&page_size=500&search=kubernetes-microservices
```
so it says forbidden for `https://www.udemy.com/api-2.0/users/me/subscribed-courses?fields[course]=id,url,title,published_title&page=1&page_size=500&search=kubernetes-microservices` , but when I open this url in the browser (that I retrieved the token from): `{"count":1,"next":null,"previous":null,"results":[{"_class":"course","id":1813098,"title":"Kubernetes Hands-On - Deploy Microservices to the AWS Cloud","url":"/course/kubernetes-microservices/learn/","published_title":"kubernetes-microservices"}],"aggregations":null}`
I'm not sure how, but maybe somehow the token is not being passed?

**Comment by Puyodead1** [comment] 2021-12-28 17:33
> > In that case, I have no idea what the issue could be. the only thing i can think of would be something related to geo-location.
> 
> I'm not sure if it has something to do with that, this is the error that I'm getting:
> 
> ```
> [08:38:14] [udemy-downloader] [_get:856] ERROR: 403 Forbidden, retrying (attempt 8 )...
> [08:38:14] [udemy-downloader] [_get:855] ERROR: Failed request https://www.udemy.com/api-2.0/users/me/subscribed-courses?fields[course]=id,url,title,published_title&page=1&page_size=500&search=kubernetes-microservices
> [08:38:14] [udemy-downloader] [_get:856] ERROR: 403 Forbidden, retrying (attempt 9 )...
> [08:38:15] [udemy-downloader] [_subscribed_courses:591] CRITICAL: Udemy Says: 'NoneType' object has no attribute 'json' on https://www.udemy.com/api-2.0/users/me/subscribed-courses?fields[course]=id,url,title,published_title&page=1&page_size=500&search=kubernetes-microservices
> ```
> 
> so it says forbidden for `https://www.udemy.com/api-2.0/users/me/subscribed-courses?fields[course]=id,url,title,published_title&page=1&page_size=500&search=kubernetes-microservices` , but when I open this url in the browser (that I retrieved the token from): `{"count":1,"next":null,"previous":null,"results":[{"_class":"course","id":1813098,"title":"Kubernetes Hands-On - Deploy Microservices to the AWS Cloud","url":"/course/kubernetes-microservices/learn/","published_title":"kubernetes-microservices"}],"aggregations":null}`

could you send me a bearer token and the course url to test with? either through email `puyodead@protonmail.com` or discord `Puyodead#0001`

**Comment by Puyodead1** [comment] 2022-01-03 20:57
This issue is most likely caused by Cloudflare captchas, currently there's nothing I can do about it, but I am trying a few things.

**Comment by Puyodead1** [comment] 2022-01-10 18:22
Please see this comment for a solution: https://github.com/Puyodead1/udemy-downloader/issues/92#issuecomment-1008350964
I'm going to close this issue in favor of #92, feel free to comment there if you have any trouble setting up the new branch

**Closed by Puyodead1** 2022-01-10 18:22 UTC
Labels: bug, waiting-fix

**Comment by jaan143** [comment] 2022-08-06 13:43
@Puyodead1  i am getting this issue with latest version
