### ISSUE TITLE
[BUG] it does not download the attached resources or subtitles.

### ISSUE THREAD

**Issue by oijm17** [Puyodead1/udemy-downloader#75] opened 2021-11-28 04:16 UTC
**Description**
When you have already downloaded only the video files of the classes, and you run the script again, this time specifying the arguments to download all resources and all subtitles: The script does not download any of the attached resources and downloads only some subtitles from classes (very, very few).

**To Reproduce**

1. Run the script without downloading attachments or subtitles:

`python main.py -c https://www.udemy.com/courses/myawesomecourse -b <Bearer Token>`

2. Wait for it to end.
3. Run the script again, this time with the `--download-assets --download-captions -l all` arguments in order to complete the previous download with the attachments and subtitles, like this:
`python main.py -c https://www.udemy.com/courses/myawesomecourse -b <Bearer Token> --download-assets --download-captions -l all`
4. You will find that upon completion, it downloaded the subtitles for only some classes, and none of the attachments.

**Desktop:**
OS: [Windows 10, Linux Centos 8.5 Stream]
Python: [v3.9.1, v3.6.8]

**Comment by Puyodead1** [comment] 2021-11-28 04:17
> 

Are you using the `--download-assets` and `--download-captions` options?

**Comment by oijm17** [comment] 2021-11-28 04:36
> > 
> 
> Are you using the `--download-assets` and `--download-captions` options?

Of course, yes, however I just found that the problem occurs in a specific situation, I have modified the description.

**Comment by ddiiwoong** [comment] 2021-11-28 11:20
I have the same issue. URI Link is available to download directly, but aria2 have encoutered with the log. 

`Processing 1 caption(s)...
    >  Downloading caption: '029 Taints & Tolerations vs Node Affinity_en.vtt'
    > Downloading File...

11/28 20:17:04 [NOTICE] Downloading 1 item(s)

11/28 20:17:04 [ERROR] CUID#7 - Download aborted. URI=https://**************
Exception: [AbstractCommand.cc:312] errorCode=1 Network problem has occurred. cause:A socket operation was attempted to an unreachable network.    

[#9ab5a1 0B/0B CN:0 DL:0B]
11/28 20:17:05 [NOTICE] Download GID#9ab5a1a288b22063 not complete: C:/Users/rokak/udemy-downloader/out_dir/certified-kubernetes-application-developer/03 - Configuration/029 Taints & Tolerations vs Node Affinity_en.vtt

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
9ab5a1|ERR |       0B/s|C:/Users/rokak/udemy-downloader/out_dir/certified-kubernetes-application-developer/03 - Configuration/029 Taints & Tolerations vs Node Affinity_en.vtt`

**Comment by Puyodead1** [comment] 2021-11-28 18:37
> > > 
> > 
> > 
> > Are you using the `--download-assets` and `--download-captions` options?
> 
> Of course, yes, however I just found that the problem occurs in a specific situation, I have modified the description.

Would you mind posting some of the log?

**Comment by Xen0byte** [comment] 2021-12-16 13:21
Hi, I am experiencing the same issue. For me, it's generating some zero-byte HTML files instead of downloading the lecture resources.

**Comment by Puyodead1** [comment] 2021-12-16 13:26
> Hi, I am experiencing the same issue. For me, it's generating some zero-byte HTML files instead of downloading the lecture resources.

Is there anything in the console output like an error?

**Comment by Xen0byte** [comment] 2021-12-16 13:37
> > Hi, I am experiencing the same issue. For me, it's generating some zero-byte HTML files instead of downloading the lecture resources.
> 
> Is there anything in the console output like an error?

Not as far as I could tell. I'll paste here a snippet from the log in a bit.

**Comment by Xen0byte** [comment] 2021-12-16 14:17
@Puyodead1, please let me know what information I could extract that might be useful to you in debugging this issue.

**Comment by Puyodead1** [comment] 2021-12-16 18:30
> 

Thank you, this is very helpful. Would you mind sending me your bearer token and the course URL so I can do some testing? I don't know any courses I have with HTML file resources which is why I never was able to actually test it. You can email me puyodead@protonmail.com or DM me on Discord Puyodead1#001

**Comment by Xen0byte** [comment] 2021-12-16 21:57
> > 
> 
> Thank you, this is very helpful. Would you mind sending me your bearer token and the course URL so I can do some testing? I don't know any courses I have with HTML file resources which is why I never was able to actually test it. You can email me [puyodead@protonmail.com](mailto:puyodead@protonmail.com) or DM me on Discord `Puyodead1#001`

Yeah, sure thing, but I think your Discord handle is missing a digit from the identifier. Just to note that the resource is PDF, NOT HTML, but for whatever reason it's not being picked up as such.

**Comment by Puyodead1** [comment] 2021-12-16 23:06
> > > 
> > 
> > 
> > Thank you, this is very helpful. Would you mind sending me your bearer token and the course URL so I can do some testing? I don't know any courses I have with HTML file resources which is why I never was able to actually test it. You can email me [puyodead@protonmail.com](mailto:puyodead@protonmail.com) or DM me on Discord `Puyodead1#001`
> 
> Yeah, sure thing, but I think your Discord handle is missing a digit from the identifier. Just to note that the resource is PDF, not HTML, but for whatever reason it's not being picked up as such.

ah damn github tried formatting it as a number and removed a digit lmao `Puyodead#0001`

and so its a PDF that is generating empty html files?

**Comment by Xen0byte** [comment] 2021-12-17 00:33
> > > > 
> > > 
> > > 
> > > Thank you, this is very helpful. Would you mind sending me your bearer token and the course URL so I can do some testing? I don't know any courses I have with HTML file resources which is why I never was able to actually test it. You can email me [puyodead@protonmail.com](mailto:puyodead@protonmail.com) or DM me on Discord `Puyodead1#001`
> > 
> > 
> > Yeah, sure thing, but I think your Discord handle is missing a digit from the identifier. Just to note that the resource is PDF, not HTML, but for whatever reason it's not being picked up as such.
> 
> ah damn github tried formatting it as a number and removed a digit lmao `Puyodead#0001`
> 
> and so its a PDF that is generating empty html files?

Essentially, this is the page:

![2021-12-17_00-26-44](https://user-images.githubusercontent.com/6122296/146468758-59a99f8b-1e3a-4cea-996a-4b2430a101eb.png)

![2021-12-17_00-30-57](https://user-images.githubusercontent.com/6122296/146469027-1a58bce9-5e8c-42b4-9ba9-6e6e8ed792de.png)

... but the PDF is not downloaded, and instead there's this empty HTML file.

**Comment by Xen0byte** [comment] 2021-12-17 00:35
@Puyodead1 I've emailed you, in the meantime. 😊

**Comment by Puyodead1** [comment] 2021-12-17 13:52
> @Puyodead1 I've emailed you, in the meantime. 😊

I've identified the potential issue, could you please try the latest commit (8756bfc2668f688cb438db1570b7be7e57ab8cf7)
Also I noticed this specific course is rather large, if it makes it easier for testing, you can use `--save-to-file` on the first run and then `--load-from-file` on any further runs as additional arguments to reduce wait times from processing the course data

**Comment by Xen0byte** [comment] 2021-12-17 14:18
> > @Puyodead1 I've emailed you, in the meantime. 😊
> 
> I've identified the potential issue, could you please try the latest commit ([8756bfc](https://github.com/Puyodead1/udemy-downloader/commit/8756bfc2668f688cb438db1570b7be7e57ab8cf7)) Also I noticed this specific course is rather large, if it makes it easier for testing, you can use `--save-to-file` on the first run and then `--load-from-file` on any further runs as additional arguments to reduce wait times from processing the course data

Nice! I will most likely have a look sometime tomorrow. Also, thanks for the pointer on saving to and loading from file.

**Comment by Xen0byte** [comment] 2021-12-19 10:41
Hi @Puyodead1, the PDFs are downloading fine now, but 0-byte HTML files are still being generated or downloaded too. It's not a massive problem, since I can just get rid of them all at the end, but it's indicative of an issue which may have additional implications.

**Comment by Puyodead1** [comment] 2021-12-20 17:38
> 

That's odd, is it the same course you provided in your email? If so, could you tell me the exact command you're using (ofc censor any sensitive stuff). During my testing, I only downloaded assets and it didn't produce any html files

**Comment by Xen0byte** [comment] 2021-12-21 11:59
> > Hi @Puyodead1, the PDFs are downloading fine now, but 0-byte HTML files are still being generated or downloaded too. It's not a massive problem, since I can just get rid of them all at the end, but it's indicative of an issue that may have additional implications.
> > UPDATE: So far, it seems to be just that one course, so it's possible that it may be structured in a different way from most other ones.
> 
> That's odd, is it the same course you provided in your email? If so, could you tell me the exact command you're using (ofc censor any sensitive stuff). During my testing, I only downloaded assets and it didn't produce any html files

Yes, it's that course. Apparently, if you only download assets then it doesn't reproduce, but if you use the full `python main.py --course-url <Course URL> --download-assets` command, then I believe you should see the issue.

**Comment by Puyodead1** [comment] 2021-12-21 19:02
> 

Huh, okay. Could you send me a new bearer token for testing? If you prefer Discord, my correct tag is `Puyodead1#0001`

**Comment by Xen0byte** [comment] 2021-12-21 22:37
@Puyodead1 I'm not sure if I'm doing something wrong, but the handle doesn't seem to work. I'll email you another token.

![image](https://user-images.githubusercontent.com/6122296/147006553-2a68dbe2-5bb6-4f43-beb6-b65f39046a12.png)

**Comment by Puyodead1** [comment] 2021-12-21 22:43
> @Puyodead1 I'm not sure if I'm doing something wrong, but the handle doesn't seem to work. I'll email you another token.
> 
> ![image](https://user-images.githubusercontent.com/6122296/147006553-2a68dbe2-5bb6-4f43-beb6-b65f39046a12.png)

OH, haha. `Puy❄dead1#0001` give that a try. 🤦🏻

**Comment by Puyodead1** [comment] 2021-12-21 23:22
@Xen0byte Resolved in bc9f6ecb1a40aa0aa5eaed66e9935a7d582f9a76
@oijm17 If you continue to have this issue, please open a new issue.

**Closed by Puyodead1** 2021-12-21 23:22 UTC
Labels: bug

**Comment by Foxtrod89** [comment] 2023-09-22 15:54
**--download-assets** ignores ***.py** assets

**Comment by Puyodead1** [comment] 2023-09-22 16:55
> **--download-assets** ignores ***.py** assets, [from this one](https://www.udemy.com/web-scraping-extracting-price-data-for-market-research/)

It doesn't ignore anything, if it's an attachment on a lecture it will be downloaded. If you have errors, make a new issue.
